;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="UI.Invemtory",NewTagName="UI.Inventory")
+GameplayTagRedirects=(OldTagName="Status.Defense.Toughness",NewTagName="Status.Defense.Armor")
+GameplayTagRedirects=(OldTagName="Skin.Cosmetics.Hair",NewTagName="Skin.Cosmetics.Head")
+GameplayTagRedirects=(OldTagName="UI.Widget.TalentTree",NewTagName="UI.Widget.PandoraTree")
+GameplayTagRedirects=(OldTagName="Status.Freeze",NewTagName="Status.Frostbite")
+GameplayTagRedirects=(OldTagName="Status.Frozen",NewTagName="Status.Frostbite")
+GameplayTagRedirects=(OldTagName="Status.Resistance.Freeze",NewTagName="Status.Resistance.Frostbite")
+GameplayTagRedirects=(OldTagName="Status.Resistance.FreezeLevel",NewTagName="Status.Resistance.FrostbiteLevel")
+GameplayTagRedirects=(OldTagName="Status.Shock",NewTagName="Status.ElectricShock")
+GameplayTagRedirects=(OldTagName="Status.Shocked",NewTagName="Status.ElectricShock")
+GameplayTagRedirects=(OldTagName="Status.Resistance.Shock",NewTagName="Status.Resistance.ElectricShock")
+GameplayTagRedirects=(OldTagName="Status.Resistance.ShockLevel",NewTagName="Status.Resistance.ElectricShockLevel")
+GameplayTagList=(Tag="Action.Attack",DevComment="")
+GameplayTagList=(Tag="Action.Equip",DevComment="")
+GameplayTagList=(Tag="Action.HitReact",DevComment="")
+GameplayTagList=(Tag="Action.Interact",DevComment="")
+GameplayTagList=(Tag="Action.RangedAttack",DevComment="")
+GameplayTagList=(Tag="Action.Unequip",DevComment="")
+GameplayTagList=(Tag="Cooldown",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.Shield",DevComment="")
+GameplayTagList=(Tag="Cooldown.ShootGreenFire",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Data.Mana",DevComment="SetByCaller mana recovery magnitude tag.")
+GameplayTagList=(Tag="Status.Experience",DevComment="")
+GameplayTagList=(Tag="Status.Level",DevComment="")
+GameplayTagList=(Tag="Status.MaxExperience",DevComment="")
+GameplayTagList=(Tag="Status.Point.Agility",DevComment="")
+GameplayTagList=(Tag="Status.Point.Defense",DevComment="")
+GameplayTagList=(Tag="Status.Point.Offense",DevComment="")
+GameplayTagList=(Tag="Status.Point.PandoraForce",DevComment="")
+GameplayTagList=(Tag="Status.Point.Resistance",DevComment="")
+GameplayTagList=(Tag="Status.Point.Resource",DevComment="")
+GameplayTagList=(Tag="Data.StatUp",DevComment="")
+GameplayTagList=(Tag="Effect.HitReaction",DevComment="Damage effect asset tag that triggers hit reaction.")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.FillShield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.FillShield.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.Shield.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.ShieldBubble",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FireGun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.GreenFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.GreenFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldBubble",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldDown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldUp",DevComment="")
+GameplayTagList=(Tag="Input.Ability",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Skill1",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Skill2",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Skill3",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Skill4",DevComment="")
+GameplayTagList=(Tag="Input.Native.Aim",DevComment="")
+GameplayTagList=(Tag="Input.Native.Attack",DevComment="")
+GameplayTagList=(Tag="Input.Native.Crouch",DevComment="")
+GameplayTagList=(Tag="Input.Native.Interact",DevComment="")
+GameplayTagList=(Tag="Input.Native.Jump",DevComment="")
+GameplayTagList=(Tag="Input.Native.Look",DevComment="")
+GameplayTagList=(Tag="Input.Native.Move",DevComment="")
+GameplayTagList=(Tag="Input.Native.OpenInfoUi",DevComment="")
+GameplayTagList=(Tag="Input.Native.SelectPandora",DevComment="")
+GameplayTagList=(Tag="Item.Consumable",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.HealPotion",DevComment="")
+GameplayTagList=(Tag="Item.Equipment",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Bottom",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Earring",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Hat",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Hat.HornedHelmet",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Hat.IronHelmet",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Necklace",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Ring",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Ring.GoldenRing",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Rune",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Shoes",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Top",DevComment="")
+GameplayTagList=(Tag="Item.Valuable",DevComment="")
+GameplayTagList=(Tag="Item.Valuable.SimpleKey",DevComment="")
+GameplayTagList=(Tag="Item.Weapon",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Axe.GoldAxe",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Axe.GreatAxe",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Bow.LoyalBow",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Dagger.LoyalDagger",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.GreatSword.LoyalGreatSword",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Gun.Pistol",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Gun.Rifle",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Sword.LoyalSword",DevComment="")
+GameplayTagList=(Tag="Notifier.Attack.ComboInputClose",DevComment="")
+GameplayTagList=(Tag="Notifier.Attack.ComboInputOpen",DevComment="")
+GameplayTagList=(Tag="Notifier.Attack.NextCombo",DevComment="")
+GameplayTagList=(Tag="Notifier.DeleteWeapon",DevComment="")
+GameplayTagList=(Tag="Notifier.SpawnWeapon",DevComment="")
+GameplayTagList=(Tag="Pandora.Defensive",DevComment="")
+GameplayTagList=(Tag="Pandora.Defensive.Steel",DevComment="")
+GameplayTagList=(Tag="Pandora.Offensive",DevComment="")
+GameplayTagList=(Tag="Pandora.Offensive.Fire",DevComment="")
+GameplayTagList=(Tag="Pandora.Offensive.Freeze",DevComment="")
+GameplayTagList=(Tag="Pandora.Offensive.Lightning",DevComment="")
+GameplayTagList=(Tag="Pandora.Special",DevComment="")
+GameplayTagList=(Tag="Pandora.Support",DevComment="")
+GameplayTagList=(Tag="Pandora.Support.Light",DevComment="")
+GameplayTagList=(Tag="Pandora.Support.Nature",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Aura",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Back",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Bottom",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Bottom.Green",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Face",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Hat",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Hat.PrettyHat",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Head",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Shoes",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Top",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Top.OrangeShirt",DevComment="")
+GameplayTagList=(Tag="Skin.Gesture",DevComment="")
+GameplayTagList=(Tag="Skin.Gesture.Greeting",DevComment="")
+GameplayTagList=(Tag="Skin.Pandora",DevComment="")
+GameplayTagList=(Tag="Skin.Riding",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Equipping",DevComment="")
+GameplayTagList=(Tag="State.HitReacting",DevComment="")
+GameplayTagList=(Tag="State.Unequipping",DevComment="")
+GameplayTagList=(Tag="Status.Agility.AttackSpeed",DevComment="")
+GameplayTagList=(Tag="Status.Agility.CriticalChance",DevComment="")
+GameplayTagList=(Tag="Status.Agility.CriticalDamageMultiplier",DevComment="")
+GameplayTagList=(Tag="Status.Agility.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Status.Buff.MaxShield",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Defense.Armor",DevComment="")
+GameplayTagList=(Tag="Status.Defense.MagicResistance",DevComment="")
+GameplayTagList=(Tag="Status.Defense.Recovery",DevComment="")
+GameplayTagList=(Tag="Status.Offense.Arcane",DevComment="")
+GameplayTagList=(Tag="Status.Offense.Intelligence",DevComment="")
+GameplayTagList=(Tag="Status.Offense.Strength",DevComment="")
+GameplayTagList=(Tag="Status.PandoraForce.FirstPandora",DevComment="")
+GameplayTagList=(Tag="Status.PandoraForce.SecondPandora",DevComment="")
+GameplayTagList=(Tag="Status.PandoraForce.ThirdPandora",DevComment="")
+GameplayTagList=(Tag="Status.Resistance.Fortitude",DevComment="")
+GameplayTagList=(Tag="Status.Resistance.Immunity",DevComment="")
+GameplayTagList=(Tag="Status.Resistance.Sanity",DevComment="")
+GameplayTagList=(Tag="Status.Resource.Health",DevComment="")
+GameplayTagList=(Tag="Status.Resource.Mana",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxMana",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxShield",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxStamina",DevComment="")
+GameplayTagList=(Tag="Status.Resource.Stamina",DevComment="")
+GameplayTagList=(Tag="Status.StaminaRegen",DevComment="")
+GameplayTagList=(Tag="Status.Agility.Arcane",DevComment="Arcane stat tag.")
+GameplayTagList=(Tag="Status.Agility.ArcaneLevel",DevComment="Arcane investment level tag.")
+GameplayTagList=(Tag="Status.Agility.AttackSpeedLevel",DevComment="Attack speed investment level tag.")
+GameplayTagList=(Tag="Status.Agility.MovementSpeedLevel",DevComment="Movement speed investment level tag.")
+GameplayTagList=(Tag="Status.Defense.ArmorLevel",DevComment="Armor investment level tag.")
+GameplayTagList=(Tag="Status.Defense.MaxShield",DevComment="Maximum shield defense stat tag.")
+GameplayTagList=(Tag="Status.Defense.MaxShieldIncreasePercent",DevComment="Maximum shield increase percent stat tag.")
+GameplayTagList=(Tag="Status.Defense.MaxShieldLevel",DevComment="Maximum shield investment level tag.")
+GameplayTagList=(Tag="Status.Defense.RecoveryLevel",DevComment="Recovery investment level tag.")
+GameplayTagList=(Tag="Status.Offense.Critical",DevComment="Critical stat tag.")
+GameplayTagList=(Tag="Status.Offense.CriticalLevel",DevComment="Critical investment level tag.")
+GameplayTagList=(Tag="Status.Offense.IntelligenceLevel",DevComment="Intelligence investment level tag.")
+GameplayTagList=(Tag="Status.Offense.StrengthLevel",DevComment="Strength investment level tag.")
+GameplayTagList=(Tag="Status.PandoraForce.FirstPandoraLevel",DevComment="First pandora force investment level tag.")
+GameplayTagList=(Tag="Status.PandoraForce.SecondPandoraLevel",DevComment="Second pandora force investment level tag.")
+GameplayTagList=(Tag="Status.PandoraForce.ThirdPandoraLevel",DevComment="Third pandora force investment level tag.")
+GameplayTagList=(Tag="Status.Resistance.Burn",DevComment="Burn stat tag.")
+GameplayTagList=(Tag="Status.Resistance.BurnLevel",DevComment="Burn investment level tag.")
+GameplayTagList=(Tag="Status.Resistance.ElectricShock",DevComment="Electric shock resistance stat tag.")
+GameplayTagList=(Tag="Status.Resistance.ElectricShockLevel",DevComment="Electric shock resistance investment level tag.")
+GameplayTagList=(Tag="Status.Resistance.Frostbite",DevComment="Frostbite resistance stat tag.")
+GameplayTagList=(Tag="Status.Resistance.FrostbiteLevel",DevComment="Frostbite resistance investment level tag.")
+GameplayTagList=(Tag="Status.Resource.MaxHealthIncreasePercent",DevComment="Maximum health increase percent stat tag.")
+GameplayTagList=(Tag="Status.Resource.MaxHealthLevel",DevComment="Maximum health investment level tag.")
+GameplayTagList=(Tag="Status.Resource.MaxManaIncreasePercent",DevComment="Maximum mana increase percent stat tag.")
+GameplayTagList=(Tag="Status.Resource.MaxManaLevel",DevComment="Maximum mana investment level tag.")
+GameplayTagList=(Tag="Status.Resource.MaxStaminaIncreasePercent",DevComment="Maximum stamina increase percent stat tag.")
+GameplayTagList=(Tag="Status.Resource.MaxStaminaLevel",DevComment="Maximum stamina investment level tag.")
+GameplayTagList=(Tag="UI.Equipment",DevComment="")
+GameplayTagList=(Tag="UI.HUD",DevComment="")
+GameplayTagList=(Tag="UI.Info",DevComment="")
+GameplayTagList=(Tag="UI.Inventory",DevComment="")
+GameplayTagList=(Tag="UI.PandoraEquipment",DevComment="")
+GameplayTagList=(Tag="UI.PandoraInventory",DevComment="")
+GameplayTagList=(Tag="UI.Profile",DevComment="")
+GameplayTagList=(Tag="UI.SkinEquipment",DevComment="")
+GameplayTagList=(Tag="UI.SkinInventory",DevComment="")
+GameplayTagList=(Tag="UI.Status",DevComment="")
+GameplayTagList=(Tag="UI.Widget.PlayerHUD",DevComment="")
