;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Data.Operation",NewTagName="Data.StatUp")
+GameplayTagRedirects=(OldTagName="Item.Weapon.Sword.LongSword",NewTagName="Item.Weapon.Sword.LoyalSword")
+GameplayTagRedirects=(OldTagName="Item.Weapon.Sword.Greatsword",NewTagName="Item.Weapon.Sword.LoyalGreatsword")
+GameplayTagRedirects=(OldTagName="Item.Weapon.Sword.Dagger",NewTagName="Item.Weapon.Sword.LoyalDagger")
+GameplayTagList=(Tag="Action.Attack",DevComment="")
+GameplayTagList=(Tag="Action.Equip",DevComment="")
+GameplayTagList=(Tag="Action.Interact",DevComment="")
+GameplayTagList=(Tag="Action.Unequip",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.StatUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReact",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.HealPotion",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Bottom",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Earring",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Hat.HornedHelmet",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Hat.IronHelmet",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Necklace",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Ring",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Ring.GoldenRing",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Rune",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Shoes",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Top",DevComment="")
+GameplayTagList=(Tag="Item.Valuable.SimpleKey",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Dagger.LoyalDagger",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.GreatSword.LoyalGreatSword",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Sword.LoyalSword",DevComment="")
+GameplayTagList=(Tag="Notifier.Attack.ComboInputClose",DevComment="")
+GameplayTagList=(Tag="Notifier.Attack.ComboInputOpen",DevComment="")
+GameplayTagList=(Tag="Notifier.Attack.NextCombo",DevComment="")
+GameplayTagList=(Tag="Notifier.DeleteWeapon",DevComment="")
+GameplayTagList=(Tag="Notifier.SpawnWeapon",DevComment="")
+GameplayTagList=(Tag="Pandora.Defensive",DevComment="")
+GameplayTagList=(Tag="Pandora.Defensive.Steel",DevComment="")
+GameplayTagList=(Tag="Pandora.Offensive",DevComment="")
+GameplayTagList=(Tag="Pandora.Offensive.Fire",DevComment="")
+GameplayTagList=(Tag="Pandora.Special",DevComment="")
+GameplayTagList=(Tag="Pandora.Support",DevComment="")
+GameplayTagList=(Tag="Pandora.Support.Light",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Aura",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Back",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Bottom",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Face",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Hair",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Hat",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Hat.PrettyHat",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Shoes",DevComment="")
+GameplayTagList=(Tag="Skin.Cosmetics.Top",DevComment="")
+GameplayTagList=(Tag="Skin.Gesture",DevComment="")
+GameplayTagList=(Tag="Skin.Gesture.Greeting",DevComment="")
+GameplayTagList=(Tag="Skin.Pandora",DevComment="")
+GameplayTagList=(Tag="Skin.Riding",DevComment="")
+GameplayTagList=(Tag="State.Attack.Active",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Equipping",DevComment="")
+GameplayTagList=(Tag="State.HitReacting",DevComment="")
+GameplayTagList=(Tag="State.Unequipping",DevComment="")
+GameplayTagList=(Tag="Status.Agility.AttackSpeed",DevComment="")
+GameplayTagList=(Tag="Status.Agility.CriticalChance",DevComment="")
+GameplayTagList=(Tag="Status.Agility.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Status.Defense.MagicResistance",DevComment="")
+GameplayTagList=(Tag="Status.Defense.Recovery",DevComment="")
+GameplayTagList=(Tag="Status.Defense.Toughness",DevComment="")
+GameplayTagList=(Tag="Status.Offense.Arcane",DevComment="")
+GameplayTagList=(Tag="Status.Offense.Intelligence",DevComment="")
+GameplayTagList=(Tag="Status.Offense.Strength",DevComment="")
+GameplayTagList=(Tag="Status.PandoraForce.FirstPandora",DevComment="")
+GameplayTagList=(Tag="Status.PandoraForce.SecondPandora",DevComment="")
+GameplayTagList=(Tag="Status.PandoraForce.ThirdPandora",DevComment="")
+GameplayTagList=(Tag="Status.Resistance.Fortitude",DevComment="")
+GameplayTagList=(Tag="Status.Resistance.Immunity",DevComment="")
+GameplayTagList=(Tag="Status.Resistance.Sanity",DevComment="")
+GameplayTagList=(Tag="Status.Resource.Health",DevComment="")
+GameplayTagList=(Tag="Status.Resource.Mana",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxMana",DevComment="")
+GameplayTagList=(Tag="Status.Resource.MaxStamina",DevComment="")
+GameplayTagList=(Tag="Status.Resource.Stamina",DevComment="")
+GameplayTagList=(Tag="UI.Equipment",DevComment="")
+GameplayTagList=(Tag="UI.HUD",DevComment="")
+GameplayTagList=(Tag="UI.Info",DevComment="")
+GameplayTagList=(Tag="UI.Invemtory",DevComment="")
+GameplayTagList=(Tag="UI.PandoraEquipment",DevComment="")
+GameplayTagList=(Tag="UI.PandoraInventory",DevComment="")
+GameplayTagList=(Tag="UI.Profile",DevComment="")
+GameplayTagList=(Tag="UI.SkinEquipment",DevComment="")
+GameplayTagList=(Tag="UI.SkinInventory",DevComment="")
+GameplayTagList=(Tag="UI.Status",DevComment="")

